title: Arrow Theme
author: cspablocortez
url: "https://cspablocortez.github.io"                             # your domain name
baseurl: "/arrow-jekyll-theme"                         # leave blank if hosted at the root
timezone: America/Los_Angeles
description: >-
  Arrow is a text-first Jekyll theme featuring minimal CSS 
  by relying on default browser stylesheets to produce highly readable, 
  responsive websites and blogs.
  
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  
exclude:
  - devlog.md